/**
 * useBLETiming.ts
 * Core Elite — BLE timing event → WatermelonDB outbox write
 *
 * This hook is the final stage of the timing pipeline:
 *
 *   CoreBluetooth delegate (iOS) / BluetoothGattCallback (Android)
 *     → clock_gettime_nsec_np() / SystemClock.uptimeNanos()   [C++ / Kotlin — ns precision]
 *     → BLETimingBuffer::enqueue()                            [C++ / lock-free queue]
 *     → CallInvoker::invokeAsync()                            [JS-thread dispatch]
 *     → bleTimingService.onTimingResult()                     [decoded TimingResult]
 *     → useBLETiming                                          [this hook]
 *     → WatermelonDB outbox write with HLC timestamp          [durable local storage]
 *     → PowerSync → Supabase                                  [server sync]
 *
 * Usage in a React Native station screen:
 *
 *   const { bleState, lastResult, isConnected } = useBLETiming({
 *     stationId:    station.id,
 *     eventId:      event.id,
 *     athleteId:    scannedAthlete?.id ?? null,
 *     drillId:      station.drill_id,
 *     onResult:     (result) => setDisplayTime(result.time_seconds),
 *     hlcTick,         // from the app's HLC module
 *     outboxWrite,     // WatermelonDB write function
 *   });
 *
 * Design decisions:
 *   - HLC tick is injected (not imported) to avoid coupling this package to
 *     the main app's HLC module. The app passes its own hlcTick() function.
 *   - outboxWrite is injected for the same reason — the app controls the
 *     WatermelonDB database instance.
 *   - The hook starts scanning on mount if autoScan = true (default).
 *   - All subscriptions are cleaned up on unmount — no memory leaks.
 *
 * Zero JS timing guarantee:
 *   - No Date.now() call in the result-write path.
 *   - monotonic_ns from the native layer is preserved as-is.
 *   - The HLC tick (injected) uses the app's HLC which must also avoid
 *     raw Date.now() for conflict-resolution timestamps (v2 §3.1.3).
 *   - received_at (ISO wall clock) is written for display purposes only
 *     and is explicitly excluded from conflict resolution.
 */

import { useEffect, useRef, useState, useCallback } from 'react';
import { bleTimingService } from './index';
import type { TimingResult } from './index';
import type { BLEStateChangeEvent, DeviceConnectionEvent, DeviceDisconnectionEvent } from './NativeBLETimingModule';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * OutboxRecord — the shape written to WatermelonDB.
 * Mirrors the timing_results schema with the HLC timestamp column.
 *
 * The consumer (app code) maps this to their specific WatermelonDB Model
 * using the outboxWrite function.
 */
export type TimingOutboxRecord = {
  /** Application-layer unique ID — from TimingResult.id (no Date.now). */
  client_result_id: string;

  /** Station that captured this result. */
  station_id: string;

  /** Event this result belongs to. */
  event_id: string;

  /** Athlete this result is attributed to. Null until athlete is scanned. */
  athlete_id: string | null;

  /** Drill identifier (e.g. 'forty_yard', 'pro_agility', 'vertical'). */
  drill_id: string;

  /** Elapsed time in seconds decoded from the BLE packet. */
  time_seconds: number;

  /** Source hardware chip ID ('FREELAP_A1B2', 'DASHR_001'). */
  chip_id: string;

  /**
   * Hardware monotonic timestamp as a string (nanoseconds).
   * iOS:     clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW)
   * Android: SystemClock.uptimeNanos()
   *
   * Use for intra-session elapsed-time comparisons only.
   * NOT for cross-device ordering — use hlc_timestamp for that.
   */
  monotonic_ns_str: string;

  /**
   * HLC timestamp — the authoritative write timestamp for conflict resolution.
   * Format: "{pt:016d}_{l:010d}_{nodeId}" (v3 §3.1.2).
   * Generated by the injected hlcTick() at the moment of DB write.
   * Lexicographically sortable — standard B-Tree index gives correct order.
   */
  hlc_timestamp: string;

  /**
   * ISO-8601 wall-clock string. For display only ("captured at 2:34 PM").
   * NOT used for conflict resolution — see hlc_timestamp.
   */
  received_at: string;

  /** Raw BLE bytes as hex string — preserved for debugging and re-decoding. */
  raw_hex: string;

  /** Outbox delivery status. Matches offline.ts OutboxItem.status. */
  status: 'pending';

  /** Attempt counter — incremented by the sync engine on each retry. */
  retry_count: 0;

  /** Validation gate result from the four-gate pipeline (v2 §2.2.4). */
  validation_valid: boolean;
  validation_reason?: string;
  validation_flagged_value?: number;
};

/** Function the app provides to write a record to WatermelonDB. */
export type OutboxWriteFn = (record: TimingOutboxRecord) => Promise<void>;

/** Function the app provides to generate an HLC timestamp string. */
export type HLCTickFn = () => string;

export type BLEConnectionState =
  | 'idle'
  | 'scanning'
  | 'connected'
  | 'disconnected'
  | 'error'
  | 'bluetooth_off'
  | 'unauthorized';

export interface UseBLETimingOptions {
  /** Station context — written into every outbox record. */
  stationId:    string;
  eventId:      string;

  /**
   * Current athlete being timed. Pass null when no athlete is queued.
   * The hook does not block on null — it writes the record with athlete_id = null
   * so timing data is never lost. The station UI should always show a warning
   * when athleteId is null.
   */
  athleteId:    string | null;

  /** Drill type — determines which validation gates apply. */
  drillId:      string;

  /**
   * Peripheral name prefix to scan for.
   * 'FREELAP' for Freelap FxChip, 'DASHR' for Dashr|Blue.
   * Defaults to 'FREELAP'.
   */
  scanPrefix?:  string;

  /**
   * If true, startScan() is called automatically on mount.
   * Set to false if you want to control scan start manually via startScan().
   * Defaults to true.
   */
  autoScan?:    boolean;

  /**
   * Injected HLC tick function from the app's HLC module (v2 §3.1.3).
   * Called exactly once per timing result at the moment of outbox write.
   * Must generate a string of format "{pt:016d}_{l:010d}_{nodeId}".
   */
  hlcTick:      HLCTickFn;

  /**
   * Injected WatermelonDB write function.
   * The app controls the database instance and the Model mapping.
   * See TimingOutboxRecord for the data shape.
   */
  outboxWrite:  OutboxWriteFn;

  /**
   * Optional callback invoked synchronously after a TimingResult is decoded
   * and before the outbox write. Use to update UI (e.g. display the time).
   * Do not perform heavy work here — it runs on the JS thread during the
   * timing event delivery window.
   */
  onResult?:    (result: TimingResult) => void;

  /**
   * Optional callback invoked after the outbox write completes.
   * Use to trigger sync, update UI state, or advance the athlete queue.
   */
  onWritten?:   (record: TimingOutboxRecord) => void;

  /**
   * Optional callback invoked if the outbox write throws.
   * The timing result is NOT lost — the caller should retry or surface the error.
   */
  onWriteError?: (error: unknown, result: TimingResult) => void;
}

export interface UseBLETimingReturn {
  /** Current BLE adapter / connection state. */
  bleState:     BLEConnectionState;

  /** Most recently decoded and validated timing result. Null before first event. */
  lastResult:   TimingResult | null;

  /** True when at least one peripheral is connected. */
  isConnected:  boolean;

  /** Manually start scanning. Called automatically on mount if autoScan = true. */
  startScan:    () => void;

  /** Stop scanning and disconnect all peripherals. */
  stopScan:     () => void;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useBLETiming(options: UseBLETimingOptions): UseBLETimingReturn {
  const {
    stationId,
    eventId,
    athleteId,
    drillId,
    scanPrefix   = 'FREELAP',
    autoScan     = true,
    hlcTick,
    outboxWrite,
    onResult,
    onWritten,
    onWriteError,
  } = options;

  const [bleState,    setBleState]    = useState<BLEConnectionState>('idle');
  const [lastResult,  setLastResult]  = useState<TimingResult | null>(null);
  const [isConnected, setIsConnected] = useState(false);

  // Stable refs for injected callbacks — avoids re-subscribing on every render
  // when the parent component re-renders with new inline function references.
  const hlcTickRef      = useRef(hlcTick);
  const outboxWriteRef  = useRef(outboxWrite);
  const onResultRef     = useRef(onResult);
  const onWrittenRef    = useRef(onWritten);
  const onWriteErrorRef = useRef(onWriteError);

  useEffect(() => { hlcTickRef.current      = hlcTick;      }, [hlcTick]);
  useEffect(() => { outboxWriteRef.current  = outboxWrite;  }, [outboxWrite]);
  useEffect(() => { onResultRef.current     = onResult;     }, [onResult]);
  useEffect(() => { onWrittenRef.current    = onWritten;    }, [onWritten]);
  useEffect(() => { onWriteErrorRef.current = onWriteError; }, [onWriteError]);

  // Station context in a ref — changes don't trigger re-subscribe
  const stationIdRef  = useRef(stationId);
  const eventIdRef    = useRef(eventId);
  const athleteIdRef  = useRef(athleteId);
  const drillIdRef    = useRef(drillId);

  useEffect(() => { stationIdRef.current  = stationId;  }, [stationId]);
  useEffect(() => { eventIdRef.current    = eventId;    }, [eventId]);
  useEffect(() => { athleteIdRef.current  = athleteId;  }, [athleteId]);
  useEffect(() => { drillIdRef.current    = drillId;    }, [drillId]);

  // ---------------------------------------------------------------------------
  // Core timing result handler
  //
  // Called by bleTimingService on the JS thread after the native buffer flushes
  // via CallInvoker::invokeAsync() (iOS) / runOnJSQueueThread() (Android).
  //
  // This function must be fast — it runs in the timing event delivery window.
  // The HLC tick and outbox write are the only operations performed here.
  // ---------------------------------------------------------------------------
  const handleTimingResult = useCallback(async (result: TimingResult) => {
    // Update display state synchronously (no await — instant UI feedback)
    setLastResult(result);

    // Notify the station screen immediately (before the async outbox write)
    onResultRef.current?.(result);

    // Generate the HLC timestamp NOW — at the moment of write, not at the
    // moment the event was received. The monotonic_ns on the result is the
    // hardware precision timestamp; the HLC timestamp is for cross-device
    // conflict resolution (v2 §3.1.3, v3 §3.1.2).
    const hlc_timestamp = hlcTickRef.current();

    const record: TimingOutboxRecord = {
      client_result_id:      result.id,
      station_id:            stationIdRef.current,
      event_id:              eventIdRef.current,
      athlete_id:            athleteIdRef.current,
      drill_id:              drillIdRef.current,
      time_seconds:          result.time_seconds,
      chip_id:               result.chip_id,
      monotonic_ns_str:      result.monotonic_ns.toString(),
      hlc_timestamp,
      received_at:           result.received_at,
      raw_hex:               result.raw_hex,
      status:                'pending',
      retry_count:           0,
      validation_valid:      result.validation.valid,
      ...(!result.validation.valid && {
        validation_reason:         result.validation.reason,
        validation_flagged_value:  result.validation.flagged_value,
      }),
    };

    try {
      await outboxWriteRef.current(record);
      onWrittenRef.current?.(record);
    } catch (err) {
      // Write failure — surface to caller. The timing result is in `record`
      // and can be retried. Do not silently discard (v1 §3.6.4: add-biased LWW,
      // never silently delete a timing result).
      onWriteErrorRef.current?.(err, result);
    }
  }, []); // Stable — all mutable state accessed via refs

  // ---------------------------------------------------------------------------
  // BLE state / connection listeners
  // ---------------------------------------------------------------------------
  useEffect(() => {
    const unsubState = bleTimingService.onBLEStateChange((event: BLEStateChangeEvent) => {
      switch (event.state) {
        case 'poweredOn':    setBleState('scanning'); break;
        case 'poweredOff':   setBleState('bluetooth_off'); break;
        case 'unauthorized': setBleState('unauthorized'); break;
        default:             setBleState('idle'); break;
      }
    });

    const unsubConnect = bleTimingService.onDeviceConnected((_event: DeviceConnectionEvent) => {
      setIsConnected(true);
      setBleState('connected');
    });

    const unsubDisconnect = bleTimingService.onDeviceDisconnected((_event: DeviceDisconnectionEvent) => {
      setIsConnected(false);
      setBleState('disconnected');
      // The native layer handles exponential backoff reconnect automatically.
      // After MAX_RECONNECT_ATTEMPTS the native layer emits onScanError.
    });

    const unsubError = bleTimingService.onError(() => {
      setBleState('error');
      setIsConnected(false);
    });

    const unsubResult = bleTimingService.onTimingResult(handleTimingResult);

    if (autoScan) {
      bleTimingService.startScan(scanPrefix);
      setBleState('scanning');
    }

    return () => {
      unsubState();
      unsubConnect();
      unsubDisconnect();
      unsubError();
      unsubResult();
      bleTimingService.stopScan();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Subscribe once — all mutable values accessed via refs

  const startScan = useCallback(() => {
    bleTimingService.startScan(scanPrefix);
    setBleState('scanning');
  }, [scanPrefix]);

  const stopScan = useCallback(() => {
    bleTimingService.stopScan();
    setBleState('idle');
  }, []);

  return { bleState, lastResult, isConnected, startScan, stopScan };
}
